"""
Response schemas for LLM Service

Defines the structured data formats for LLM provider responses.
These Pydantic models are used internally to parse and validate LLM outputs
before converting to API response schemas defined in resume_schema.py.

Using pydantic.BaseModel (instead of dataclass) enables with_structured_output()
in LangChain, which generates a JSON Schema from the model and passes it to
Gemini's Function Calling API to guarantee structured output.
"""

from typing import List, Optional
from pydantic import BaseModel, Field


class Suggestion(BaseModel):
    """
    Single improvement suggestion from LLM analysis.

    Attributes:
        category: Type of suggestion (e.g., "content", "skills", "formatting")
        priority: Importance level - "high", "medium", or "low"
        title: Brief summary of the suggestion
        description: Detailed explanation of what to improve and why
        example: Optional Before/After example (for analyze)
        action: Optional specific action to take (for match)
    """

    category: str = Field(description="Type of suggestion, e.g. content/skills/format/language")
    priority: str = Field(description="Importance level: high, medium, or low")
    title: str = Field(description="Brief title, max 10 words")
    description: str = Field(description="Detailed explanation of the improvement")
    example: Optional[str] = Field(default=None, description="Before vs After example (for analyze)")
    action: Optional[str] = Field(default=None, description="Specific action to take (for match)")


class AnalyzeResult(BaseModel):
    """
    Result from resume analysis operation.

    Contains a list of suggestions for improving the resume's overall quality,
    independent of any specific job description.
    """

    suggestions: List[Suggestion] = Field(default_factory=list)


class MatchBreakdown(BaseModel):
    """
    Detailed breakdown of resume-JD match score by category.

    Each score is a percentage (0-100). Field constraints replace the manual
    max(0, min(100, ...)) clamp that was previously done in _parse_match_score.
    """

    skills_match: int = Field(default=0, ge=0, le=100)
    experience_match: int = Field(default=0, ge=0, le=100)
    education_match: int = Field(default=0, ge=0, le=100)
    keywords_match: int = Field(default=0, ge=0, le=100)


class MatchResult(BaseModel):
    """
    Result from resume-JD matching operation.

    Contains overall match score, detailed breakdown by category,
    and suggestions for improving alignment with the job description.
    """

    match_score: int = Field(default=0, ge=0, le=100)
    match_breakdown: MatchBreakdown = Field(default_factory=MatchBreakdown)
    suggestions: List[Suggestion] = Field(default_factory=list)


class OptimizeResult(BaseModel):
    """
    Result from resume optimization operation.

    Contains the optimized resume content generated by the LLM,
    in Markdown format ready for PDF conversion.
    """

    optimized_content: str = ""
